#################
# MAIN parameters
#################
input:  # (.xlsx OR .csv) metafile with fastq path.
output: # Set the OUTPUT directory
genome: # Ref genome indexed with bwa mem2
ncores: 34 # Number of cores
##################

##################
variant_calling: false
dbsnp: /data/delcorvo/tools/dbsnp138.vcf.gz
dbsnp_tbi: /data/delcorvo/tools/dbsnp138.vcf.gz.tbi
##################

########################
## trimmomatic params ##
########################
params:
  trimmomatic:
      pe:
        trimmer:
          # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
          - "LEADING:30"
          - "TRAILING:30"
          - "SLIDINGWINDOW:4:30"
          - "MINLEN:35"
          - "TOPHRED33"
      se:
        trimmer:
          # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
          - "LEADING:30"
          - "TRAILING:30"
          - "SLIDINGWINDOW:4:30"
          - "MINLEN:35"
          - "TOPHRED33"

#######################
## read depth params ##
#######################

chrs:
  chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY
binSize:  1000000 # set window size to compute coverage
qual: 20

#####################
## ichorCNA params ##
#####################

ichorCNA_gcWig: data/ichorCNA_extdata/gc_hg38_1000kb.wig # must use gc wig file corresponding to same binSize (required)
ichorCNA_mapWig:  data/ichorCNA_extdata/map_hg38_1000kb.wig # must use map wig file corresponding to same binSize (required)
ichorCNA_centromere:  data/ichorCNA_extdata/GRCh38.GCA_000001405.2_centromere_acen.txt
ichorCNA_minMapScore: 0.75
ichorCNA_fracReadsInChrYForMale: 0.002

#######################################
# Internal parameters (do not change..)
#######################################
derived_data: derived_data
final_data: final_data
metadata: docs
logs: logs
benchmarks: benchmarks
annotation: data/annotation
##################