name: DeSeq-Free_workflow
channels:
  - defaults
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python=3.11.9
  - conda>=24.7.1
  - conda-forge::mamba
  - anaconda::openpyxl
  - anaconda::pandas
  - anaconda::numpy
  - pip
  - pip:
      - snakemake